#ifndef XITENGINE_ENUMS
#define XITENGINE_ENUMS

enum MemoryType {
    MEM_INT,
    MEM_FLOAT,
    MEM_DOUBLE,
    MEM_LONG,
    MEM_BYTE,
    MEM_TWO_BYTES,
    MEM_FOUR_BYTES,
    MEM_EIGHT_BYTES
};

enum ScanType {
    EXACT_VALUE,
    BIGGER_THAN,
    SMALLER_THAN,
    VALUE_BETWEEN,
    INCREASED, //CANT BE USED ON FIRST SCAN
    DECREASED, //CANT BE USED ON FIRST SCAN
    CHANGED, //CANT BE USED ON FIRST SCAN
    UNCHANGED //CANT BE USED ON FIRST SCAN
};

#endif